### ISSUE TITLE
The Colab Notebook doesn't work

### ISSUE THREAD

**Issue by janeyen** [shtoshni92/long-doc-coref#1]
Hi,

I wanted to quickly try out the functionality with the provided colab Notebook. However, it raised some attribute error.
`AttributeError: 'BertTokenizerFast' object has no attribute 'convert_tokens_to_string'`
What should I do to resolve the problem? Thanks!

**Comment by shtoshni** [comment]
Should be working now, it had to do with the version of transformers. I changed the code to use BertTokenizerFast which didn't support the "convert_tokens_to_string" method in the 3.0.0 version of transformers. Changed it to 4.2.2. now.
